const allProjets = [
  {
    name: "Virtu'Art",
    description: `
    Virtu'Art est notre premier projet dans le cadre de la formation à la Wild Code School.
    `,
    description2: `
    Consigne :
    LE SITE :
    Le site tient sur une page /
    Le site ressemble aux wireframes (maquettes) /
    Le site ne contient que des ressources valides (libres / gratuites / personnelles) /
    Le site est déployé (GitHub Pages) /
    LE CODE : 
    Le code ne se répète pas et ne contient pas de code mort (code propre) /
    Le code est valide (W3C Validator) /
    Le code est disponible sur GitHub /
    Les commits sont clairs et explicites
    `,
    description3: `
    Appréciation : Woaw ! Quelle masterclass ! Bravo ! N'hésitez pas à le fork pour les personnes qui ne l'ont pas et à le partager sur les réseaux, car c'est magnifique !
    `,
    github: "https://github.com/fanny-pretre/art-galery-2",
    online: "https://fanny-pretre.github.io/art-galery-2/",
    lien: "",
    mates: "Fanny PrêTre, David Lanzetti, NICOLAS",
    id: "1",
    upload: "yes",
    category: "projets",
    img: "https://github.com/fanny-pretre/art-galery-2/blob/main/assets/oeuvre/Banksy.jpg?raw=true",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "Globe Guide",
    description: "Projet 2",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github:
      "https://github.com/WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team1",
    online: "https://globe-guide.netlify.app/",
    lien: "",
    mates: "Fanny PrêTre, Mohamed Jebri, Baptiste Cazenave, Laurent",
    id: "2",
    upload: "yes",
    category: "projets",
    img: "https://github.com/WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team1/blob/dev/client/src/assets/images/Gif.gif?raw=true",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "",
    description: "Projet 3",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "3",
    upload: "no",
    category: "projets",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "Checkpoint 1",
    description: "",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "4",
    upload: "yes",
    category: "checkPoints",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "Checkpoint 2",
    description: "",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "5",
    upload: "no",
    category: "checkPoints",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "",
    description: "",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "6",
    upload: "no",
    category: "ateliers",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "",
    description: "",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "7",
    upload: "no",
    category: "quetes",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
  {
    name: "Casino",
    description:
      "Site pour jouer au pierre feuille ciseau et aux dés en js vanilla",
    description2: "Description supplémentaire 1",
    description3: "Description supplémentaire 2",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "8",
    upload: "no",
    category: "projetsPerso",
    img: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
    img6: "",
    img7: "",
    img8: "",
    img9: "",
    img10: "",
  },
];

export default allProjets;
