const allProjets = [
  {
    name: "Virtu'Art",
    description: "Projet 1",
    github: "https://github.com/fanny-pretre/art-galery-2",
    online: "https://fanny-pretre.github.io/art-galery-2/",
    lien: "",
    mates: "Fanny PrêTre, David Lanzetti, NICOLAS",
    id: "1",
    upload: "yes",
    category: "projets",
    img: "https://github.com/fanny-pretre/art-galery-2/blob/main/assets/oeuvre/Banksy.jpg?raw=true",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "Globe Guide",
    description: "Projet 2",
    github:
      "https://github.com/WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team1",
    online: "https://globe-guide.netlify.app/",
    lien: "",
    mates: "Fanny PrêTre, Mohamed Jebri, Baptiste Cazenave, Laurent",
    id: "2",
    upload: "yes",
    category: "projets",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "",
    description: "Projet 3",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "3",
    upload: "no",
    category: "projets",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "Checkpoint 1",
    description: "",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "4",
    upload: "yes",
    category: "checkPoints",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "Checkpoint 2",
    description: "",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "5",
    upload: "no",
    category: "checkPoints",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "",
    description: "",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "6",
    upload: "no",
    category: "ateliers",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "",
    description: "",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "7",
    upload: "no",
    category: "quetes",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
  {
    name: "Casino",
    description:
      "Site pour jouer au pierre feuille ciseau et aux dés en js vanilla",
    github: "",
    online: "",
    lien: "",
    mates: "",
    id: "8",
    upload: "no",
    category: "projetsPerso",
    img: "img1",
    img2: "img2",
    img3: "img3",
    img4: "img4",
    img5: "img5",
    img6: "img6",
    img7: "img7",
    img8: "img8",
    img9: "img9",
    img10: "img10",
  },
];

export default allProjets;
